# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Done',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=12),
        ),
    ]
